### PR TITLE
fix HTTPResponse#to_s using stringio

### PR DESCRIPTION
**Pull request by thekuwayama**
Hi!

This PR fixes `WEBrick::HTTPResponse#to_s`.
The following code that is according to the `HTTPResponse#to_s` document raises an error.

```
irb(main):001:0> require 'webrick'
=> true
irb(main):002:0> res = WEBrick::HTTPResponse.new(HTTPVersion: '1.1')
=> #<WEBrick::HTTPResponse:0x00007feae59e0868 @config={:HTTPVersion=>"1.1"}, @buffer_size=nil, @logger=nil, @header={}, @status=200, @reason_phrase=nil, @http_version=#<WEBrick::HTTPVersion:0x00007feae59e0818 @minor=1, @major=1>, @body="", @keep_alive=true, @cookies=[], @request_method=nil, @request_uri=nil, @request_http_version=#<WEBrick::HTTPVersion:0x00007feae59e0818 @minor=1, @major=1>, @chunked=false, @filename=nil, @sent_size=0>
irb(main):003:0> res.body = 'hoge'
=> "hoge"
irb(main):004:0> res.to_s
Traceback (most recent call last):
        7: from /Users/thekuwayama/.rbenv/versions/2.6.3/bin/irb:23:in `<main>'
        6: from /Users/thekuwayama/.rbenv/versions/2.6.3/bin/irb:23:in `load'
        5: from /Users/thekuwayama/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from /Users/thekuwayama/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpresponse.rb:323:in `to_s'
        2: from /Users/thekuwayama/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpresponse.rb:208:in `send_response'
        1: from /Users/thekuwayama/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpresponse.rb:217:in `rescue in send_response'
NoMethodError (undefined method `error' for nil:NilClass)
```

### CODE REVIEW

**Comment by jeremyevans** [comment]
Considering https://bugs.ruby-lang.org/issues/10715 and the fact this method is nodoc, maybe it would be better to remove the method?

**Comment by thekuwayama** [comment]
@jeremyevans I don't disagree with that, but I'm worried that it is used somewhere.

**Comment by jeremyevans** [comment]
It looks like this method was broken in fadf140a907ee4c2a95984f1ce154ec35f528905.  So it probably worked in 2.5 and broke in 2.6.  I don't think we've had any reports in the last 6 months about it no longer working, so there probably aren't many people relying on it.  Since it hasn't been broken for more than one release, removing it is more of a gray area.  I would still vote to remove it, though.

**Comment by thekuwayama** [comment]
That makes sense. 😃 
I close this PR.
